- Makefile
- test.sh
This PR creates `Makefile` to test, lint, and format.
> CHORE: Create Makefile

- pfhedge/instruments/primary/brownian.py
- pfhedge/instruments/primary/heston.py
Change default initial state from `(1.0, 0.04)` to `(1.0, theta)`.
> Change default init state of HestonStock

- pfhedge/nn/modules/bs/american_binary.py
- pfhedge/nn/modules/bs/european.py
- pfhedge/nn/modules/bs/european_binary.py
- pfhedge/nn/modules/bs/lookback.py
> DOC: Add reference to BS price formula #129

- .github/workflows/ci.yml
- .github/workflows/doc.yml
- pfhedge/_utils/hook.py
> CHORE: Support PyTorch 1.10

- README.md
- docs/source/index.rst
> CHORE: Update README.md

- docs/source/nn.functional.rst
- pfhedge/nn/functional.py
- pfhedge/nn/modules/loss.py
> ENH: Add `entropic_risk_measure` to nn.functional (close #352)

- docs/source/nn.functional.rst
- pfhedge/nn/functional.py
- tests/nn/test_functional.py
> ENH: Add `value_at_risk` to nn.functional

- .gitignore
- examples/example_plot_american_binary.py
- examples/example_plot_european.py
- examples/example_plot_european_binary.py
- examples/example_plot_lookback.py
- pfhedge/instruments/primary/brownian.py
- pfhedge/nn/functional.py
- pfhedge/nn/modules/bs/american_binary.py
- pfhedge/nn/modules/bs/european.py
- pfhedge/nn/modules/bs/european_binary.py
- pfhedge/nn/modules/bs/lookback.py
- tests/nn/bs/_utils.py
- tests/nn/bs/test_american_binary.py
- tests/nn/bs/test_european.py
- tests/nn/bs/test_european_binary.py
- tests/nn/bs/test_lookback.py
- tests/nn/modules/test_ww.py
> TEST: Add more tests to BS modules and fix BSAmericanBinaryOption (#366)

- pfhedge/nn/modules/clamp.py
> MAINT: Update repr of LeakyClamp

- docs/Makefile
> CHORE: Update Makefile

- pfhedge/nn/functional.py
- pfhedge/nn/modules/hedger.py
- pfhedge/nn/modules/ww.py
- tests/nn/modules/test_ww.py
> MAINT: Add Whalley-Wilmott width to functional

- pfhedge/nn/functional.py
> MAINT: Fix documentation

- tests/nn/bs/test_american_binary.py
> TEST: Add Monte Carlo test with continuity correction

- tests/nn/bs/test_european.py
- tests/nn/bs/test_european_binary.py
> MAINT: Refactor tests

- examples/example_heston_iv.py
- examples/requirements.txt
- tests/nn/bs/test_european_binary.py
> DOC: Add `example_heston_iv.py`

- .gitignore
> MAINT: Add examples/output/

- .github/workflows/ci.yml
- .github/workflows/examples.yml
> TEST: Test that the examples work (close #108)

- pfhedge/nn/modules/hedger.py
- tests/test_examples.py
> ENH: Enable customizing tqdm progress bar

- pfhedge/stochastic/__init__.py
- pfhedge/stochastic/random.py
- tests/stochastic/test_randn.py
> WIP: ENH: Add antithetic sampling of randn (close #449)

- docs/source/nn.functional.rst
- docs/source/nn.rst
- examples/example_svi.py
- pfhedge/instruments/primary/brownian.py
- pfhedge/nn/__init__.py
- pfhedge/nn/functional.py
- pfhedge/nn/modules/svi.py
- pfhedge/stochastic/brownian.py
- pfhedge/stochastic/cir.py
- pfhedge/stochastic/heston.py
- tests/features/test_features.py
- tests/instruments/primary/test_brownian.py
- tests/nn/modules/test_svi.py
- tests/stochastic/test_cir.py
> ENH: Add SVI model (#406)

- pfhedge/instruments/derivative/base.py
- tests/instruments/derivative/test_european.py
related to #274 #495 
Opposite method to list()
> added Derivative.delist

- docs/source/instruments.rst
- docs/source/nn.functional.rst
- pfhedge/instruments/__init__.py
- pfhedge/instruments/derivative/cliquet.py
- pfhedge/nn/functional.py
- tests/instruments/derivative/test_cliquet.py
- tests/instruments/derivative/test_european.py
> ENH: Add European forward start option (#443)

- docs/source/nn.functional.rst
- pfhedge/nn/functional.py
- pfhedge/nn/modules/bs/american_binary.py
- pfhedge/nn/modules/bs/european.py
- pfhedge/nn/modules/bs/european_binary.py
- pfhedge/nn/modules/bs/lookback.py
> ENH: Add Black-Scholes formulas as functional (#489)

- pfhedge/nn/functional.py
y in Tensor.where should not be scalar 0.0 due to PyTorch bug: https://github.com/pytorch/pytorch/issues/73298
PR will fix this https://github.com/pytorch/pytorch/pull/62084
> MAINT: Use variance

- pfhedge/instruments/primary/base.py
- pfhedge/instruments/primary/brownian.py
- pfhedge/instruments/primary/cir.py
- pfhedge/instruments/primary/heston.py
- pfhedge/nn/modules/bs/_base.py
> MAINT: Fix primary spot typing (#530)

- poetry.toml
> fix Poetry issue 609

- tests/nn/modules/test_svi.py
https://github.com/pytorch/ pytorch /issues/61844
> remove assert_allclose and use assert_close instead
